apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask-container
      image: flask-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
