apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
            - name: api-key-secret-volume
              mountPath: /app/api_key.json
              subPath: api_key.json
      volumes:
        - name: config-volume
          configMap:
            name: greeting-config
        - name: api-key-secret-volume
          secret:
            secretName: api-key-secret
